### ISSUE TITLE
Should be possible to send answers to external APIs

### ISSUE THREAD

**Issue by EirikOsnes** [knowit/kompetansekartlegging-gui#1]
- [x] Expose API for adding new FormDefinitions 
- [x] Authorize access to exposed API
- [x] Expose API for fetching result data
- [x] Set up event based push of data

**Comment by EirikOsnes** [comment]
Event based is set up, but no external api's exist to push to atm.
