### ISSUE TITLE
A user should be able to fill out a form and send it in.

### ISSUE THREAD

**Issue by EirikOsnes** [knowit/kompetansekartlegging-gui#11]
- [x] Be shown a form to fill out
- [x] Be able to fill out the form
- [x] Be able to submit the form
- [x] Get feedback that the form is submitted

- [x] #30 Allow for multiple types of Questions per topic

**Comment by EirikOsnes** [comment]
#8
